/*
 * Deterministic frame pattern self-test (TEMPORARY debugging aid).
 *
 * When CONFIG_LLSS_PATTERN_TEST is enabled, the firmware appends
 * "&pattern=1" to the frame fetch and the backend returns a synthetic 1bpp
 * packed framebuffer generated by the SAME integer formula implemented here.
 * That lets us verify the received bytes byte-for-byte at each pipeline stage
 * and visually confirm geometry on the SDL/native_sim display.
 *
 * The pattern (pixel == 1 means white) is deliberately asymmetric so any
 * mis-placement is unambiguous on screen:
 *   - 1px border around the whole frame
 *   - solid 64x64 white square in the TOP-LEFT corner (orientation marker)
 *   - thick 24px white stripe along the TOP (so "bottom-on-top" is glaring)
 *   - 1px diagonal from top-left to bottom-right
 *   - horizontal ruler tick every 40 rows
 *
 * Keep this file in lockstep with eink_llss/app/frame_converter.py
 * pattern_framebuffer_1bpp(): the byte stream MUST be identical.
 */
#ifndef LLSS_PATTERN_CHECK_H_
#define LLSS_PATTERN_CHECK_H_

#include <stddef.h>
#include <stdint.h>

#define PATTERN_W      800
#define PATTERN_H      480
#define PATTERN_STRIDE (PATTERN_W / 8)            /* 100 bytes/row */
#define PATTERN_BYTES  (PATTERN_STRIDE * PATTERN_H) /* 48000 */
#define PATTERN_CANARY 0xC5u

/* Expected packed byte at linear index `i` (0..PATTERN_BYTES-1). */
uint8_t pattern_expected_byte(size_t i);

/*
 * Compare `len` bytes of `buf` against the expected pattern.
 * Logs the first mismatch as byte index + (x,y) + exp/got and the total diff
 * count. Returns 0 on full match, -1 otherwise. `stage` tags the log line.
 */
int pattern_verify(const uint8_t *buf, size_t len, const char *stage);

/* Fill `len` bytes of `region` with the canary byte (call once at init). */
void pattern_canary_fill(uint8_t *region, size_t len);

/*
 * Verify `len` canary bytes are intact. Logs the first corrupted offset.
 * Returns 0 if intact, -1 otherwise.
 */
int pattern_canary_verify(const uint8_t *region, size_t len, const char *stage);

#endif /* LLSS_PATTERN_CHECK_H_ */
